/**
 * Subject Content Service
 * Sprint Subj-4 - Learning Paths & Queries
 *
 * Provides hydrated content queries and learning path generation
 * for subject-based content discovery.
 */

import { prisma } from '../db';
import { getDescendants, type ContentType, type SubjectContentQuery } from './subjects';

// =============================================================================
// Types
// =============================================================================

export interface HydratedMilestone {
  id: string;
  title: string;
  description: string;
  date: Date;
  category: string;
  significance: number;
  organizationId: string | null;
  sourceUrl: string | null;
  tags: string;
  tldr: string | null;
}

export interface HydratedGlossaryTerm {
  id: string;
  term: string;
  shortDefinition: string;
  fullDefinition: string;
  category: string | null;
}

export interface HydratedCurrentEvent {
  id: string;
  headline: string;
  summary: string;
  publishedAt: Date;
  sourceUrl: string | null;
}

export interface HydratedPerson {
  id: string;
  canonicalName: string;
  slug: string;
  shortBio: string;
  role: string | null;
  focusAreas: string;
  imageUrl: string | null;
}

export interface HydratedOrganization {
  id: string;
  name: string;
  slug: string;
  shortDescription: string;
  type: string;
  focusAreas: string;
  logoUrl: string | null;
}

export interface SubjectContent {
  milestones: HydratedMilestone[];
  glossaryTerms: HydratedGlossaryTerm[];
  currentEvents: HydratedCurrentEvent[];
  persons: HydratedPerson[];
  organizations: HydratedOrganization[];
  total: number;
}

export interface GeneratedLearningPath {
  title: string;
  slug: string;
  description: string;
  targetAudience: string;
  difficulty: string;
  estimatedMinutes: number;
  milestoneIds: string[];
  conceptsCovered: string[];
  keyTakeaways: string[];
  isAutoGenerated: boolean;
  subjectSlug?: string;
  crossSubjectSlugs?: string[];
}

// =============================================================================
// Content Query Functions
// =============================================================================

/**
 * Get hydrated content for a subject
 * Fetches actual content objects, not just IDs
 */
export async function getContentBySubject(
  subjectSlug: string,
  options: SubjectContentQuery = {}
): Promise<SubjectContent> {
  if (!prisma) throw new Error('Database not available');

  // Get the subject
  const subject = await prisma.subject.findUnique({
    where: { slug: subjectSlug },
  });

  if (!subject) {
    return {
      milestones: [],
      glossaryTerms: [],
      currentEvents: [],
      persons: [],
      organizations: [],
      total: 0,
    };
  }

  // Get subject IDs to query (including children if requested)
  let subjectIds = [subject.id];
  if (options.includeChildren) {
    const descendants = await getDescendants(subject.id);
    subjectIds = [...subjectIds, ...descendants.map(d => d.id)];
  }

  // Determine which content types to query
  const contentTypes = options.contentTypes || [
    'milestone',
    'glossary_term',
    'current_event',
    'person',
    'organization',
  ];

  // Build base query for ContentSubject
  const baseWhere = {
    subjectId: { in: subjectIds },
    ...(options.primaryOnly ? { isPrimary: true } : {}),
  };

  const result: SubjectContent = {
    milestones: [],
    glossaryTerms: [],
    currentEvents: [],
    persons: [],
    organizations: [],
    total: 0,
  };

  // Fetch each content type
  if (contentTypes.includes('milestone')) {
    const milestoneLinks = await prisma.contentSubject.findMany({
      where: { ...baseWhere, contentType: 'milestone' },
      select: { contentId: true, confidence: true },
      distinct: ['contentId'],
    });

    if (milestoneLinks.length > 0) {
      const milestones = await prisma.milestone.findMany({
        where: { id: { in: milestoneLinks.map(l => l.contentId) } },
        select: {
          id: true,
          title: true,
          description: true,
          date: true,
          category: true,
          significance: true,
          organizationId: true,
          sourceUrl: true,
          tags: true,
          tldr: true,
        },
        orderBy: options.sortBy === 'significance'
          ? { significance: 'desc' }
          : options.sortBy === 'date'
            ? { date: 'desc' }
            : { date: 'desc' },
        take: options.limit,
        skip: options.offset,
      });

      result.milestones = milestones;
    }
  }

  if (contentTypes.includes('glossary_term')) {
    const glossaryLinks = await prisma.contentSubject.findMany({
      where: { ...baseWhere, contentType: 'glossary_term' },
      select: { contentId: true },
      distinct: ['contentId'],
    });

    if (glossaryLinks.length > 0) {
      const terms = await prisma.glossaryTerm.findMany({
        where: { id: { in: glossaryLinks.map(l => l.contentId) } },
        select: {
          id: true,
          term: true,
          shortDefinition: true,
          fullDefinition: true,
          category: true,
        },
        orderBy: { term: 'asc' },
        take: options.limit,
        skip: options.offset,
      });

      result.glossaryTerms = terms;
    }
  }

  if (contentTypes.includes('current_event')) {
    const eventLinks = await prisma.contentSubject.findMany({
      where: { ...baseWhere, contentType: 'current_event' },
      select: { contentId: true },
      distinct: ['contentId'],
    });

    if (eventLinks.length > 0) {
      const events = await prisma.currentEvent.findMany({
        where: { id: { in: eventLinks.map(l => l.contentId) } },
        select: {
          id: true,
          headline: true,
          summary: true,
          publishedDate: true,
          sourceUrl: true,
        },
        orderBy: { publishedDate: 'desc' },
        take: options.limit,
        skip: options.offset,
      });

      result.currentEvents = events;
    }
  }

  if (contentTypes.includes('person')) {
    const personLinks = await prisma.contentSubject.findMany({
      where: { ...baseWhere, contentType: 'person' },
      select: { contentId: true },
      distinct: ['contentId'],
    });

    if (personLinks.length > 0) {
      const persons = await prisma.person.findMany({
        where: { id: { in: personLinks.map(l => l.contentId) } },
        select: {
          id: true,
          canonicalName: true,
          slug: true,
          shortBio: true,
          role: true,
          focusAreas: true,
          imageUrl: true,
        },
        orderBy: { canonicalName: 'asc' },
        take: options.limit,
        skip: options.offset,
      });

      result.persons = persons;
    }
  }

  if (contentTypes.includes('organization')) {
    const orgLinks = await prisma.contentSubject.findMany({
      where: { ...baseWhere, contentType: 'organization' },
      select: { contentId: true },
      distinct: ['contentId'],
    });

    if (orgLinks.length > 0) {
      const orgs = await prisma.organization.findMany({
        where: { id: { in: orgLinks.map(l => l.contentId) } },
        select: {
          id: true,
          name: true,
          slug: true,
          shortDescription: true,
          type: true,
          focusAreas: true,
          logoUrl: true,
        },
        orderBy: { name: 'asc' },
        take: options.limit,
        skip: options.offset,
      });

      result.organizations = orgs;
    }
  }

  result.total =
    result.milestones.length +
    result.glossaryTerms.length +
    result.currentEvents.length +
    result.persons.length +
    result.organizations.length;

  return result;
}

// =============================================================================
// Learning Path Generation
// =============================================================================

/**
 * Generate a learning path from a subject's content
 * Creates a chronological journey through the subject's milestones
 */
export async function generateSubjectLearningPath(
  subjectSlug: string
): Promise<GeneratedLearningPath | null> {
  if (!prisma) throw new Error('Database not available');

  const subject = await prisma.subject.findUnique({
    where: { slug: subjectSlug },
  });

  if (!subject) return null;

  // Get milestones for this subject (primary only to avoid tangents)
  const milestoneLinks = await prisma.contentSubject.findMany({
    where: {
      subjectId: subject.id,
      contentType: 'milestone',
      isPrimary: true,
    },
    select: { contentId: true },
  });

  const milestones = await prisma.milestone.findMany({
    where: { id: { in: milestoneLinks.map(l => l.contentId) } },
    orderBy: { date: 'asc' },
    take: 20, // Limit to reasonable path length
  });

  // Get related glossary terms
  const glossaryLinks = await prisma.contentSubject.findMany({
    where: {
      subjectId: subject.id,
      contentType: 'glossary_term',
    },
    select: { contentId: true },
  });

  const glossaryTerms = await prisma.glossaryTerm.findMany({
    where: { id: { in: glossaryLinks.map(l => l.contentId) } },
    select: { term: true },
  });

  // Generate key takeaways from milestone titles
  const keyTakeaways = generateKeyTakeaways(milestones, subject.name);

  return {
    title: `History of ${subject.name}`,
    slug: `subject-${subject.slug}`,
    description: `Explore the key milestones in ${subject.name}, from early developments to recent breakthroughs.`,
    targetAudience: `Anyone interested in ${subject.name}`,
    difficulty: (subject.defaultDifficulty as string) || 'intermediate',
    estimatedMinutes: milestones.length * 5, // 5 minutes per milestone
    milestoneIds: milestones.map(m => m.id),
    conceptsCovered: glossaryTerms.map(t => t.term),
    keyTakeaways,
    isAutoGenerated: true,
    subjectSlug: subject.slug,
  };
}

/**
 * Generate a learning path spanning multiple subjects
 */
export async function generateCrossSubjectPath(
  subjectSlugs: string[],
  options: { title?: string; maxMilestones?: number } = {}
): Promise<GeneratedLearningPath | null> {
  if (!prisma) throw new Error('Database not available');

  const subjects = await prisma.subject.findMany({
    where: { slug: { in: subjectSlugs } },
  });

  if (subjects.length === 0) return null;

  // Get all milestones for these subjects
  const milestoneLinks = await prisma.contentSubject.findMany({
    where: {
      subjectId: { in: subjects.map(s => s.id) },
      contentType: 'milestone',
    },
    select: { contentId: true },
    distinct: ['contentId'],
  });

  const milestones = await prisma.milestone.findMany({
    where: { id: { in: milestoneLinks.map(l => l.contentId) } },
    orderBy: { date: 'asc' },
    take: options.maxMilestones || 20,
  });

  const subjectNames = subjects.map(s => s.name).join(' & ');

  // Generate key takeaways
  const keyTakeaways = generateKeyTakeaways(milestones, subjectNames);

  return {
    title: options.title || `${subjectNames}: A Combined History`,
    slug: `cross-${subjectSlugs.join('-')}`,
    description: `Explore how ${subjectNames} have evolved together through key milestones.`,
    targetAudience: `Anyone interested in ${subjectNames}`,
    difficulty: 'intermediate',
    estimatedMinutes: milestones.length * 5,
    milestoneIds: milestones.map(m => m.id),
    conceptsCovered: [],
    keyTakeaways,
    isAutoGenerated: true,
    crossSubjectSlugs: subjectSlugs,
  };
}

/**
 * Generate key takeaways from milestones
 */
function generateKeyTakeaways(
  milestones: { title: string; significance: number; date: Date }[],
  subjectName: string
): string[] {
  const takeaways: string[] = [];

  if (milestones.length === 0) {
    return [`Explore the history of ${subjectName}`];
  }

  // Get date range
  const firstYear = milestones[0]?.date.getFullYear();
  const lastYear = milestones[milestones.length - 1]?.date.getFullYear();
  if (firstYear && lastYear) {
    takeaways.push(`Understand ${subjectName} from ${firstYear} to ${lastYear}`);
  }

  // Get most significant milestones
  const significant = milestones
    .filter(m => m.significance >= 3)
    .slice(0, 3);

  for (const m of significant) {
    takeaways.push(`Learn about ${m.title}`);
  }

  // If we still need more, add generic ones
  if (takeaways.length < 3) {
    takeaways.push(`Trace the evolution of key concepts in ${subjectName}`);
  }

  return takeaways.slice(0, 5);
}

// =============================================================================
// Related Content Functions
// =============================================================================

export interface RelatedContentItem {
  contentType: ContentType;
  contentId: string;
  title: string;
  overlapScore: number; // Number of shared subjects
}

/**
 * Get content that shares subjects with a given piece of content
 */
export async function getRelatedContent(
  contentType: ContentType,
  contentId: string,
  limit = 5
): Promise<RelatedContentItem[]> {
  if (!prisma) throw new Error('Database not available');

  // Get subjects for this content
  const contentSubjects = await prisma.contentSubject.findMany({
    where: { contentType, contentId },
    select: { subjectId: true },
  });

  if (contentSubjects.length === 0) return [];

  const subjectIds = contentSubjects.map(cs => cs.subjectId);

  // Find other content with same subjects
  const related = await prisma.contentSubject.findMany({
    where: {
      subjectId: { in: subjectIds },
      NOT: {
        AND: [{ contentType }, { contentId }],
      },
    },
    select: { contentType: true, contentId: true, subjectId: true },
  });

  // Score by number of overlapping subjects
  const scoreMap = new Map<string, { type: ContentType; id: string; score: number }>();

  for (const r of related) {
    const key = `${r.contentType}:${r.contentId}`;
    const existing = scoreMap.get(key);
    if (existing) {
      existing.score++;
    } else {
      scoreMap.set(key, {
        type: r.contentType as ContentType,
        id: r.contentId,
        score: 1,
      });
    }
  }

  // Sort by score and get top N
  const sorted = Array.from(scoreMap.values())
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);

  // Hydrate with titles
  const results: RelatedContentItem[] = [];

  for (const item of sorted) {
    let title = '';

    switch (item.type) {
      case 'milestone': {
        const m = await prisma.milestone.findUnique({
          where: { id: item.id },
          select: { title: true },
        });
        title = m?.title || 'Unknown Milestone';
        break;
      }
      case 'glossary_term': {
        const t = await prisma.glossaryTerm.findUnique({
          where: { id: item.id },
          select: { term: true },
        });
        title = t?.term || 'Unknown Term';
        break;
      }
      case 'current_event': {
        const e = await prisma.currentEvent.findUnique({
          where: { id: item.id },
          select: { headline: true },
        });
        title = e?.headline || 'Unknown Event';
        break;
      }
      case 'person': {
        const p = await prisma.person.findUnique({
          where: { id: item.id },
          select: { canonicalName: true },
        });
        title = p?.canonicalName || 'Unknown Person';
        break;
      }
      case 'organization': {
        const o = await prisma.organization.findUnique({
          where: { id: item.id },
          select: { name: true },
        });
        title = o?.name || 'Unknown Organization';
        break;
      }
    }

    results.push({
      contentType: item.type,
      contentId: item.id,
      title,
      overlapScore: item.score,
    });
  }

  return results;
}
